package it.newsoft.model;

// default package
// Generated 29-mag-2018 14.45.07 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Libro generated by hbm2java
 */
@Entity
@Table(name = "libro", catalog = "biblioteca")
public class Libro implements java.io.Serializable {

	private Integer idLibro;
	private String autore;
	private String titolo;
	private String casaEditrice;
	private String isbn;

	public Libro() {
	}

	public Libro(String autore, String titolo, String casaEditrice, String isbn) {
		this.autore = autore;
		this.titolo = titolo;
		this.casaEditrice = casaEditrice;
		this.isbn = isbn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdLibro", unique = true, nullable = false)
	public Integer getIdLibro() {
		return this.idLibro;
	}

	public void setIdLibro(Integer idLibro) {
		this.idLibro = idLibro;
	}

	@Column(name = "autore")
	public String getAutore() {
		return this.autore;
	}

	public void setAutore(String autore) {
		this.autore = autore;
	}

	@Column(name = "titolo")
	public String getTitolo() {
		return this.titolo;
	}

	public void setTitolo(String titolo) {
		this.titolo = titolo;
	}

	@Column(name = "casaEditrice")
	public String getCasaEditrice() {
		return this.casaEditrice;
	}

	public void setCasaEditrice(String casaEditrice) {
		this.casaEditrice = casaEditrice;
	}

	@Column(name = "isbn")
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

}
